PLAT-6198-ZU-Preview-Backup
Simovative/dbSync pull request #6
Opened 2024-05-23 13:56 UTC by simo-matthias-wieschke

2024-05-23 14:56 UTC, simo-thinterhoelzel approved these changes, later dismissed

2024-05-23 16:11 UTC, simo-ltrischberger requested changes

2024-05-23 16:11 UTC, simo-ltrischberger commented on generateDropTablesQueries.sh
> +    errxit "No excluded tables provided, exiting"
```suggestion
    errexit "No excluded tables provided, exiting"
```
gibt nur errexit

2024-05-28 07:56 UTC, simo-ltrischberger approved these changes

2024-05-28 07:57 UTC, merged